/**
 * 🌍 VI Dictionary Aggregator
 * 
 * Tổng hợp tất cả namespace thành 1 object
 * Dùng cho backward compatibility với code hiện tại
 * 
 * @auto-generated by split-dictionaries.js
 */

import common from './common.json';
import home from './home.json';
import seo from './seo.json';
import auth from './auth.json';
import dashboard from './dashboard.json';
import learn from './learn.json';
import lesson_content from './lesson-content.json';
import practice from './practice.json';
import compete from './compete.json';
import adventure from './adventure.json';
import certificate from './certificate.json';
import pricing from './pricing.json';
import tools from './tools.json';
import profile from './profile.json';
import admin from './admin.json';
import components from './components.json';

const dictionary = {
  ...common,
  ...home,
  ...seo,
  ...auth,
  ...dashboard,
  ...learn,
  ...lesson_content,
  ...practice,
  ...compete,
  ...adventure,
  ...certificate,
  ...pricing,
  ...tools,
  ...profile,
  ...admin,
  ...components,
};

export default dictionary;
