/**
 * Race Commentaries - Funny sports-style commentaries for animal races
 * Each language has its own humor style
 */

// Vietnamese commentaries (original style - slang mạng xã hội)
export const getVietnameseCommentaries = (animalType, animalName, plural, action) => ({
  start: [
    `🎙️ Xuất phát! Các ${plural} lao đi vun vút!`,
    `🎙️ Và họ đi! Nhanh như wifi nhà hàng xóm vậy!`,
    `🎙️ BOOOM! Cuộc đua thế kỷ bắt đầu! Cả vũ trụ đang theo dõi!`,
    `🎙️ Tim tôi đập loạn rồi bà con ơi! Đua thôi nào!`,
    `🎙️ Ai sẽ về đích? Ai sẽ khóc? Ai sẽ cười? Xem ngay!`,
    `🎙️ ${animalName} ơi là ${animalName.toLowerCase()}! ${action.charAt(0).toUpperCase() + action.slice(1)} thôi!`,
    `🎙️ Các ${plural} đang nghĩ: "Hôm nay tao phải thắng!"`,
    `🎙️ 3... 2... 1... Ủa đợi chút... À xong rồi! PHÓNG!`,
  ],
  leading: [
    `🔥 {name} dẫn đầu! ${action.charAt(0).toUpperCase() + action.slice(1)} nhanh quá xá!`,
    `👑 {name} đang bay! làm tim tôi lung lay!`,
    `🚀 {name} phóng nhanh vượt ẩu!`,
    `⚡ {name} nhanh đến nỗi tôi không thấy chân đâu luôn!`,
    `💪 {name} dẫn đầu cách xa... khoảng 300 năm ánh sáng!`,
    `😎 {name} số 1! number one!`,
    `💨 {name} đang dẫn đầu! bỏ xa 5 vạn 9 ngàn cây?`,
    `🎯 {name} đang nghĩ: "Các em đuổi đi, anh đợi!"`,
    `😏 {name} quay lại nhìn: "Sao đi chậm thế các bạn?"`,
    `🔥 {name} dẫn đầu! thì ai dẫn đuôi!`,
  ],
  overtake: [
    '😱 {name} vượt lên! Nhanh như tia chớp vậy!',
    '🔄 {name} lật kèo! dù hơi bèo nhèo!',
    '🎯 {name} bật turbo! Tưởng đang xem Fast & Furious!',
    '⚡ {name} vượt! Tốc độ này phải đo bằng vận tốc ánh sáng!',
    '😤 {name} vượt rồi! lêu lêu bà già!',
    '🔥 {name} bứt tốc! ai chơi lại?',
    '💥 {name} vượt! Đối thủ: "Ủa bạn đi đâu vậy?"',
    '🏆 Ai ngờ là {name}! Bất ngờ chưa bà già!',
    '💨 {name} tăng ga! Ga nào? Ga Hà Nội!',
  ],
  tired: [
    '😓 {name} đuối! Mệt như mới chạy 10 vòng trái đất!',
    '💦 {name} thở hổn hển! Như vừa leo núi!',
    '🥵 {name} kiệt sức! Như điện thoại 1% pin vậy!',
    '😴 {name} muốn ngủ! Chắc tối qua thức chơi game!',
    '😩 {name} hết xăng! Đổ đầy bình đi anh zai!',
    '💤 {name} mệt quá! Tôi nhìn cũng thấy mệt lây!',
    `🐌 {name} sao chậm vậy? Có ăn sáng chưa?`,
    '📉 {name} nghĩ: "Thôi kệ, về nhì cũng được!"',
    '🥵 {name} đuối! Đuối như con cá chuối!',
  ],
  collision: [
    '💥 {name} đụng đá! làm trái tim băng giá!',
    '😵 {name} đụng là chạm! chưa ngán ai!',
    '🤕 {name} văng! Bay xa như bóng bay tuột tay!',
    '💫 {name} thấy sao bay! lên xe ngay!',
    '🤯 {name} đâm sầm! Tiếng vang cả vũ trụ!',
    '😵‍💫 {name} chóng mặt! Tôi nhìn cũng muốn xỉu!',
    '😅 {name} tưởng đá là bạn thân hả? Ôm ghê vậy?',
    '😬 Đá: "Chào bạn!" - {name}: "Đau quá trời ơi!"',
    '🤕 {name} ăn đá! Ăn ngon không? Có cần thêm muối?',
  ],
  close: [
    '😰 Căng quá! Căng hơn cả dây thun quần!',
    '🔥 Sát nút! Sát như hai đội bóng chung kết!',
    '😱 Sát sàn sạt! Không lọt được sợi tóc!',
    '💓 Đua từng milimet! Tôi không dám thở luôn!',
    '🤯 Không tin nổi! Tay tôi run cầm không được mic!',
    '🫣 Ai thắng đây? Thần cũng không đoán được!',
    '🎬 Kịch tính quá! Đạo diễn nào viết kịch bản?',
    '⚡ Tưởng xong rồi ai ngờ vẫn còn căng!',
  ],
  halfway: [
    '🏁 Qua nửa đường! Ai tỏ tường!',
    '⏰ Mới 50%! Mà ngỡ như đã 100% chia đôi',
    '🎯 Nửa chặng! Nửa còn lại sẽ BÙNG NỔ!',
    '🔥 Qua nửa! Drama chưa bắt đầu đâu!',
    '📍 Mới nửa đường thôi à!',
    '🏁 Nửa đường rồi! Ai sẽ bung sức đây?',
    '⏰ Ủa qua nửa rồi hả? Nhanh thế!',
  ],
  final: [
    '🏆 {name} VÔ ĐỊCH! Xứng đáng như phim Marvel!',
    '🎉 {name} thắng! Đẹp như giấc mơ hồi nhỏ!',
    '👑 {name} lên ngôi! Oai như vua sư tử!',
    '🥇 {name} số 1! Cả thế giới phải ngả mũ!',
    '🌟 {name} vô địch! Vinh quang muôn đời!',
    '🤴 {name} vô địch! Tôi muốn khóc vì vui!',
    '👑 {name} VÔ ĐỊCH! Có ai xứng đáng hơn không?',
    '🥇 {name} nghĩ: "Tao nói rồi mà, tao thắng!"',
    '🏆 {name} thắng! Tưởng ai ngờ là {name}!',
  ],
  boost: [
    '🚀 {name} bật chế độ tăng động!',
    '⚡ {name} tăng tốc! Giống xe đua F1 vậy!',
    '💨 {name} bay! Máy bay cũng phải gọi bằng cụ!',
    '🔋 {name} full pin! Năng lượng vô hạn!',
    '⚡ {name} bứt tốc! Mắt tôi không theo kịp!',
    '🔥 {name} nghĩ: "Giờ mới show sức mạnh!"',
  ],
  slowdown: [
    '🌊 {name} Chậm quá! Chậm như wifi nhà tôi vậy!',
    '😓 {name} slow motion! Giống phim cô dâu 8 tuổi!',
    '🐌 {name} mất đà! ô là la!',
    '📉 {name} giảm tốc! Ôi không! Sao lại thế!',
    '🐢 {name} chậm lại! Tôi muốn khóc!',
    '😓 {name} nghĩ: "Chân ơi sao bỏ tao!"',
    '📉 {name} chậm! Ai bấm nút pause vậy?',
  ],
  comeback: [
    '🔥 {name} hồi sinh! từ vũng sình!',
    '💪 {name} comeback! quá xác oách!',
    '😤 {name} quay lại! "chờ đã, chưa xong đâu"!',
    '⚡ {name} phục hận! như con rận!',
    '🔥 {name} hồi phục! tăng tốc thôi',
    '💪 {name} bùng nổ! Nước mắt tôi rơi!',
    '🔥 Tưởng hết hy vọng! Ai ngờ {name} quay lại!',
    '😤 {name} trở lại! Come back hay back come? Kệ!',
  ],
  lucky: [
    '🍀 {name} may quá! Như trúng số vậy!',
    '✨ {name} thoát nạn! May như có bùa!',
    '😅 {name} né được! Phản xạ như như chớp!',
    '🙏 {name} may! Ông bà phù hộ chắc luôn!',
    '🍀 {name} thoát! Tim tôi rớt rồi nhặt lại!',
    '✨ Đá: "Ủa sao né được?" - {name}: "Hehe!"',
    '🙏 Tưởng đụng rồi! Ai ngờ {name} né ngon!',
  ],
  random: [
    '🔥 CÒN CÁI NỊT! Cuộc đua căng đét!',
    '💀 ĐỈNH NÓC KỊch TRẦN BAY PHẤP PHỚI!',
    '😱 XỊN XÒ NHƯ CON BÒ! Hay quá!',
    '⚡ REAL G KHÔNG BAO GIỜ BỎ CUỘC!',
    '🎯 CÁI NÀY CHÁY LẮM NHA! Quá hot!',
    '💥 NGÁO NGƠ LUÔN! Sao hay dữ vậy?',
    '😤 Ê KHÔNG ĐÙA ĐƯỢC ĐÂU! Căng thật!',
    '🎪 HẾT NƯỚC CHẤM với drama này!',
    '🚀 TỚI CÔNG CHUYỆN! Cuộc đua bắt đầu nóng lên!',
    '😎 E LÀ KHÔNG THỂ thua cuộc đua này!',
    '💯 10 ĐIỂM KHÔNG CÓ NHƯNG cho pha đua này!',
    '🎙️ Cuộc đua nóng hơn cả bếp gas đang nấu!',
    '🔥 Drama căng hơn phim hoạt hình!',
    '⚡ Tốc độ nhanh như wifi nhà người ta!',
    '🏃 Các bạn đua như shipper giao hàng nhanh!',
    '💨 Kịch tính! Cả vũ trụ đang theo dõi!',
    '🔥 Ôi trời ơi! Tôi không chịu nổi!',
    '⚔️ Tôi muốn hét lên! Hay quá!',
    '🏆 Ai sẽ thắng? Tôi cũng không biết!',
    '😂 Ủa chuyện gì đang xảy ra vậy?',
    '🔥 Đua tiếp thôi! Đua mà không về là... lạc đường!',
    '😅 Căng quá! Căng nhưng không đứt đâu!',
    '🐄 Xịn xò như con bò! Moo moo!',
    '🌪️ Tăng tốc như cơn lốc! Vèo vèo!',
    '🦊 Nhanh như sóc, tóc bay phấp phới!',
    '🎯 Đi như tên, chen lên hàng đầu!',
    '🐦 Bay như chim, tim đập thình thịch!',
    '⭐ Lao như sao băng, căng như dây đàn!',
    '🚀 Vút như tên, lên như diều gặp gió!',
    '🌊 Bơi ào ào, vào top ngay!',
    '🎵 Đua như mơ, ai ngờ hay quá!',
    '🔥 Lao như pháo, náo động cả trận!',
    '💎 Chậm mà chắc, khắc ghi chiến thắng!',
  ],
});

// English commentaries - Funny sports announcer style with puns & memes
export const getEnglishCommentaries = (animalType, animalName, plural, action) => ({
  start: [
    `🎙️ AND THEY'RE OFF! The ${plural} are zooming like they've got places to be!`,
    `🎙️ BOOM! This race is hotter than my morning coffee!`,
    `🎙️ Ladies and gentlemen, START YOUR ENGINES... wait, ${plural} don't have engines!`,
    `🎙️ The crowd goes WILD! Well, I'm going wild at least!`,
    `🎙️ 3... 2... 1... GOOOOO! May the fastest ${animalName.toLowerCase()} win!`,
    `🎙️ It's happening! My heart can't take this already!`,
    `🎙️ The ${plural} are thinking: "Today, I choose VICTORY!"`,
    `🎙️ Ready, set, CHAOS! Here we gooooo!`,
  ],
  leading: [
    `🔥 {name} is in the lead! ${action.charAt(0).toUpperCase() + action.slice(1)}ing like there's free pizza at the finish line!`,
    `👑 {name} is CRUSHING IT! Absolutely bonkers performance!`,
    `🚀 {name} zooming ahead! Did someone install rocket boosters?!`,
    `⚡ {name} is so fast, I need a slow-mo replay!`,
    `💪 {name} leading by... approximately 3 million light years!`,
    `😎 {name} is flexing! Look at that confidence!`,
    `💨 {name} leaving everyone in the DUST! Savage!`,
    `🎯 {name} is probably thinking: "Too easy, too easy!"`,
    `😏 {name} looks back and says: "Y'all coming or what?"`,
    `🔥 {name} is on FIRE! Somebody call the fire department!`,
  ],
  overtake: [
    '😱 {name} OVERTAKES! Plot twist nobody saw coming!',
    '🔄 {name} pulls off a sneaky overtake! Cheeky!',
    '🎯 {name} activates BEAST MODE! This is not a drill!',
    '⚡ {name} passes like a hot knife through butter!',
    '😤 {name} just said "Excuse me, coming through!"',
    '🔥 {name} goes BRRRR! Unstoppable!',
    '💥 {name} overtakes! Others: "Wait, that\'s illegal!"',
    '🏆 WHAT?! {name} out of nowhere!',
    '💨 {name} hits the NOS button! Fast & Furious vibes!',
  ],
  tired: [
    '😓 {name} is struggling! Running on fumes here!',
    '💦 {name} is huffing and puffing like a tired puppy!',
    '🥵 {name} is at 1% battery! Someone bring a charger!',
    '😴 {name} looks sleepy! Should\'ve had more coffee!',
    '😩 {name} running on empty! Gas station, anyone?',
    '💤 {name} is tired! I\'m getting tired just watching!',
    `🐌 {name} slowing down! Did they skip breakfast?`,
    '📉 {name} thinking: "Second place is fine, right?"',
    '🥵 {name} wilting like a flower in summer!',
  ],
  collision: [
    '💥 {name} hits a rock! That\'s gonna leave a mark!',
    '😵 {name} goes BONK! Stars everywhere!',
    '🤕 {name} crashes! Ouch ouch ouch!',
    '💫 {name} seeing stars! Tweet tweet!',
    '🤯 {name} SMASHES into obstacles! Dramatic!',
    '😵‍💫 {name} is dizzy! Round and round we go!',
    '😅 {name} hugs the rock! New best friend?',
    '😬 Rock: "Hello there!" - {name}: "OUCH!"',
    '🤕 {name} eats rock for breakfast! Crunchy!',
  ],
  close: [
    '😰 THIS IS INTENSE! Tighter than my jeans after Thanksgiving!',
    '🔥 NECK AND NECK! I can\'t look! But I must!',
    '😱 So close! A hair\'s breadth apart!',
    '💓 Photo finish incoming! My heart can\'t take it!',
    '🤯 I\'m literally shaking! Who will win?!',
    '🫣 Even the universe doesn\'t know who\'s winning!',
    '🎬 This is MOVIE material! Oscar-worthy drama!',
    '⚡ Still anyone\'s race! The suspense!',
  ],
  halfway: [
    '🏁 HALFWAY THERE! Living on a prayer!',
    '⏰ 50% done! The real drama starts NOW!',
    '🎯 Half the race, 100% the excitement!',
    '🔥 Midway point! Buckle up for the finale!',
    '📍 We\'re at halftime! Grab your snacks!',
    '🏁 50% complete! Who\'s gonna clutch it?',
    '⏰ Already halfway?! Time flies when you\'re having fun!',
  ],
  final: [
    '🏆 {name} WINS! What an absolute LEGEND!',
    '🎉 {name} crosses first! Dreams DO come true!',
    '👑 {name} is the CHAMPION! Bow down!',
    '🥇 {name} takes the gold! Pure excellence!',
    '🌟 {name} VICTORIOUS! The crowd goes insane!',
    '🤴 {name} wins! I\'m not crying, you\'re crying!',
    '👑 {name} IS THE GOAT! Greatest Of All Time!',
    '🥇 {name} thinking: "I told you so!"',
    '🏆 {name} wins! What a plot twist... or was it?',
  ],
  boost: [
    '🚀 {name} activates TURBO MODE!',
    '⚡ {name} goes into HYPERDRIVE! Zoom zoom!',
    '💨 {name} flies! Even planes are jealous!',
    '🔋 {name} at 200% power! Unlimited energy!',
    '⚡ {name} accelerates! My eyes can\'t keep up!',
    '🔥 {name}: "Now THIS is my final form!"',
  ],
  slowdown: [
    '🌊 {name} slows down! Slower than Monday morning!',
    '😓 {name} in slow-mo! Dramatic but unfortunate!',
    '🐌 {name} loses momentum! Uh oh!',
    '📉 {name} decelerates! What happened?!',
    '🐢 {name} going turtle speed! Ironic or fitting?',
    '😓 {name}: "Legs, why have you betrayed me?!"',
    '📉 {name} buffers! Did someone hit pause?',
  ],
  comeback: [
    '🔥 {name} makes a COMEBACK! Never count them out!',
    '💪 {name} returns with VENGEANCE!',
    '😤 {name} says "NOT TODAY, LOSING!"',
    '⚡ {name} rises like a PHOENIX!',
    '🔥 {name} recovers! The hero we needed!',
    '💪 {name} explodes back! What determination!',
    '🔥 Written off too soon! {name} is BACK!',
    '😤 {name} returns! Comeback of the century!',
  ],
  lucky: [
    '🍀 {name} gets LUCKY! Dodged a bullet there!',
    '✨ {name} escapes! Guardian angel on duty!',
    '😅 {name} barely misses! Cat-like reflexes!',
    '🙏 {name} is blessed! The luck is real!',
    '🍀 {name} survives! My heart dropped and recovered!',
    '✨ Rock: "How did you dodge?!" - {name}: "Skills!"',
    '🙏 Thought it was over! {name} pulls a Houdini!',
  ],
  random: [
    '🔥 THIS RACE IS BUSSIN! No cap!',
    '💀 I\'M LITERALLY DECEASED! Too good!',
    '😱 SHEEEESH! The vibes are immaculate!',
    '⚡ NO RAGRETS! Only racing!',
    '🎯 This is giving main character energy!',
    '💥 My mind is BLOWN! Incredible!',
    '😤 We\'re not playing around here!',
    '🎪 The drama is dramating!',
    '🚀 Let\'s gooooo! Maximum effort!',
    '😎 This is what peak performance looks like!',
    '💯 11/10 would recommend this race!',
    '🎙️ This race is hotter than summer in Arizona!',
    '🔥 More drama than a reality TV show!',
    '⚡ Fast like WiFi at a coffee shop!',
    '🏃 They\'re moving like it\'s Black Friday!',
    '💨 Edge of my seat! Actually fell off twice!',
    '🔥 I can\'t! I literally cannot!',
    '⚔️ Want to scream! So exciting!',
    '🏆 Who\'s gonna win? Your guess is as good as mine!',
    '😂 WHAT IS HAPPENING?!',
    '🔥 Keep racing! No quitters allowed!',
    '😅 Intense! But like, good intense!',
    '🦁 Brave like a lion! Rawr!',
    '🌪️ Speeding like a tornado! Whoooosh!',
    '🦊 Quick like a fox! Outfoxing everyone!',
    '🎯 On target like an arrow!',
    '🐦 Flying like a bird! Majestic!',
    '⭐ Shooting like a star! Magnificent!',
    '🚀 Blasting off like a rocket!',
    '🌊 Flowing like a river! Smooth!',
    '🎵 Racing like a dream! Beautiful!',
    '🔥 Blazing like fire! Hot hot hot!',
    '💎 Slow but steady wins the race! Classic!',
  ],
});

// Get commentaries based on locale
export const getCommentaries = (locale, animalType, t) => {
  // Get translated animal info from i18n
  const animalName = t(`toolbox.animalRace.animals.${animalType}.name`) || animalType;
  const plural = t(`toolbox.animalRace.animals.${animalType}.plural`) || animalType + 's';
  const action = t(`toolbox.animalRace.actions.${animalType}`) || 'move';
  
  if (locale === 'en') {
    return getEnglishCommentaries(animalType, animalName, plural, action);
  }
  return getVietnameseCommentaries(animalType, animalName, plural, action);
};
